#!/usr/bin/env ruby

args = ARGV;

if(args[0])
    path = "#{File.expand_path(File.dirname(__FILE__))}/artd-rakish/bin/artd-rakish-bin/#{args[0]}";
    if(File.exists?(path))
        puts path;
        exit 0
    end
else
    puts "d8a9e22731ea05d921473c328423e44df3fde616"
end

